[package]
name = "zk-lisp-proof"
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
zk-lisp-compiler = { path = "../zk-lisp-compiler" }
thiserror = { workspace = true }
